"""menambah kolom foto_profil

Revision ID: 17a5d3678688
Revises: 956cb77ee325
Create Date: 2026-05-16 13:06:38.422029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a5d3678688'
down_revision = '956cb77ee325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_profil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('foto_profil')

    # ### end Alembic commands ###
