"""menambahkan created_at ke users

Revision ID: 411a5d97adc5
Revises: fa8b2be33950
Create Date: 2026-06-30 00:26:27.557766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411a5d97adc5'
down_revision = 'fa8b2be33950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
