"""Update Tabel User

Revision ID: 52d7ca7fec66
Revises: b8f51f9185a3
Create Date: 2026-06-27 16:32:54.218405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d7ca7fec66'
down_revision = 'b8f51f9185a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ktp_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wedding_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_out_of_town', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_foreigner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_foreigner')
        batch_op.drop_column('is_out_of_town')
        batch_op.drop_column('wedding_city')
        batch_op.drop_column('ktp_city')

    # ### end Alembic commands ###
