"""Menambahkan tabel notif

Revision ID: 7ddda294dc4b
Revises: 52d7ca7fec66
Create Date: 2026-06-28 10:19:09.323964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ddda294dc4b'
down_revision = '52d7ca7fec66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_article_bm_uc', ['user_id', 'article_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('is_synced')
        batch_op.drop_column('wedding_date')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wedding_date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_synced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint('_user_article_bm_uc', type_='unique')

    # ### end Alembic commands ###
