"""menambahkan kolom whatsapp

Revision ID: 8c8b6055a54b
Revises: f706cd4ba3cf
Create Date: 2026-06-25 23:03:32.219056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8b6055a54b'
down_revision = 'f706cd4ba3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('whatsapp')

    # ### end Alembic commands ###
