"""tambah : kolom untuk Profil & Sinkronisasi Pasangan

Revision ID: a0783979d37b
Revises: 4f386e149b86
Create Date: 2026-06-05 18:35:47.777437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0783979d37b'
down_revision = '4f386e149b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('partner_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wedding_date', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wedding_date')
        batch_op.drop_column('partner_name')
        batch_op.drop_column('is_synced')

    # ### end Alembic commands ###
