"""tambah : kolom sistem sinkronisasi

Revision ID: c9466053026b
Revises: abc3e34b44c7
Create Date: 2026-06-05 19:05:16.497106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9466053026b'
down_revision = 'abc3e34b44c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['unique_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('unique_code')

    # ### end Alembic commands ###
