"""menambahkan tabel vendor

Revision ID: f706cd4ba3cf
Revises: d0b75e962c50
Create Date: 2026-06-24 17:26:18.046759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f706cd4ba3cf'
down_revision = 'd0b75e962c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('price_start', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('philosophy', sa.Text(), nullable=True),
    sa.Column('portfolio_urls', sa.JSON(), nullable=True),
    sa.Column('packages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    # ### end Alembic commands ###
