"""add face recognition columns

Revision ID: fa8b2be33950
Revises: 7ddda294dc4b
Create Date: 2026-06-28 17:02:38.024671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8b2be33950'
down_revision = '7ddda294dc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_embedding', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('face_registered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('face_registered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('face_registered_at')
        batch_op.drop_column('face_registered')
        batch_op.drop_column('face_embedding')

    # ### end Alembic commands ###
